### ISSUE TITLE
Is it possible to use ",," to do a reverse motion?

### ISSUE THREAD

**Issue by oakmegaeddie** [Houl/repmo-vim#10]
Hi, I see this settings in readme:

" repeat the last [count]motion or the last zap-key:
:map <expr> ; repmo#LastKey(';')|sunmap ;
:map <expr> , repmo#LastRevKey(',')|sunmap ,

However I use `,` as my leader key, so I can't use it to do a reverse motion, is it possible to map `,,` instead of `,`?

If there's other suggestion, please tell me, thx.

**Comment by Houl** [comment]
You can map `,,` as follows:

    map <expr> ,, repmo#LastRevKey('')|sunmap ,,

The readme mentions how to map `<BS>` as alternative repetition key.
