### ISSUE TITLE
repmo only remember first movement

### ISSUE THREAD

**Issue by Piping** [Houl/repmo-vim#6]
does repmo only works for first movement like `5j` and later on I used `f` and repmo will only repeat first `5j`  but not new movement .. help? 

Thanks for this awesome plugin

**Comment by Houl** [comment]
After `5j` and `f`, repetition keys `;` and `,` will repeat `f`.  You need to type `5j` again.  Or you map alternative repetition keys.

**Comment by Piping** [comment]
Thanks for you reply!

I think the current situation for me is that repmo does not update to my new movement but keep only first mapping like `5j` but not second movement `f`. 

And is it possible to add `wincmd` such as  `<C-w>-` and `<C-w>+` to the mapping?

**Comment by Houl** [comment]
Maybe I didn't get your problem ... when you map `;`, then you also need to map the `f`-like keys, otherwise `;` fails to repeat `f`.

You can map `<C-W>` key combos:

    :noremap <expr> <C-W>+ repmo#SelfKey('<C-W>+', '<C-W>-')
    :noremap <expr> <C-W>- repmo#SelfKey('<C-W>-', '<C-W>+')

**Comment by Piping** [comment]
@Houl  It does not work ...

**Comment by Houl** [comment]
I'm not sure what to assume about the "does not work" part.

So you mapped at least the keys `j`, `k`, `f`, `;` and `,` as described in the readme, and you checked the `:map` output still shows the expected right-hand-sides after startup.  And when you do `5jfc` (where `c` is some char), then `;` repeats `5j` instead of `fc`, right?  (It should indeed repeat `fc`)  And you also tried this with a minimal setup?

**Comment by Piping** [comment]
@Houl YES, exactly my situation! I tried with minimal setup, hjkl, ftFT works, but not other command like `<C-w>+` (after adding mapping), and it does not update to (remember) second movement.
I have `set timeout`, `set ttimeout` , I am not sure if it affects the plugin.

**Comment by Houl** [comment]
I followed your dotfiles.  There is an entry `Plug 'joeytwiddle/repmo.vim'`.  Is that what you use?

**Comment by Piping** [comment]
@Houl Thats the current one I used. But before I use your repmo. Did you try out the configuration?

**Comment by Houl** [comment]
[joeytwiddle/repmo.vim](https://github.com/joeytwiddle/repmo.vim) is a fork of a [fork](https://github.com/sunaku/repmo.vim) of the [predecessor](http://www.vim.org/scripts/script.php?script_id=2174) of [this](https://github.com/Houl/repmo-vim) script.  The old script is completely different.

Please check out the [README](https://github.com/Houl/repmo-vim/blob/master/README.markdown).

**Comment by Houl** [comment]
I copy-pasted [README](https://github.com/Houl/repmo-vim/blob/master/README.markdown)'s first block of mappings right from the browser into a fresh vimrc ("e_vimrc") and then started gvim with `-N -u e_vimrc -U NONE -i NONE`.  Appears to work for me.

**Comment by Piping** [comment]
@Houl Ok, I will try a new fresh setup see what's the inference! Thanks
