### ISSUE TITLE
Cannot work with vim-plug

### ISSUE THREAD

**Issue by sunfanyunn** [Houl/repmo-vim#8]
When using vim-plug(https://github.com/junegunn/vim-plug) to manage my plugins,
It does not work.

**Comment by sunfanyunn** [comment]
After adding these to .vimrc:
`Plug 'Houl/repmo-vim'`
and 
```
:noremap <expr> h repmo#SelfKey('h', 'l')|sunmap h  
:noremap <expr> l repmo#SelfKey('l', 'h')|sunmap l  
:map <expr> ; repmo#LastKey(';')|sunmap ;  
:map <expr> , repmo#LastRevKey(',')|sunmap ,  
:noremap <expr> f repmo#ZapKey('f')|sunmap f  
:noremap <expr> F repmo#ZapKey('F')|sunmap F  
:noremap <expr> t repmo#ZapKey('t')|sunmap t  
:noremap <expr> T repmo#ZapKey('T')|sunmap T  
```

**Comment by Houl** [comment]
> It does not work.

What do you mean ... do you get error messages?

**Comment by sunfanyunn** [comment]
Did not really get any error message. I simply cannot repeat motion by ;, nothing happens.
But when I use PlugStatus, it shows ```repmo-vim : OK```.

**Comment by Houl** [comment]
Check the output of `:map h|map l|map ;|map ,|map f|map F|map t|map T` to make sure keys weren't redefined.  Maybe in verbose mode: `:verb exec 'map h|map l|map ;|map ,|map f|map F|map t|map T'`.

**Comment by sunfanyunn** [comment]
![image](https://user-images.githubusercontent.com/16130918/47252467-3e3ab900-d478-11e8-807a-204967aa4946.png)

**Comment by sunfanyunn** [comment]
I am using Ubuntu 16.04 and VIM 7.4

**Comment by Houl** [comment]
[Is this your vimrc](https://github.com/petwill/dotfiles/blob/master/.vimrc)?
Probably not, it uses vundle and also loads another version of this script `Plugin 'vim-scripts/repmo.vim'`
(and it needs cleanup, lots of duplicate commands in there ... and weird order of settings ...).
Anyway: make sure to start with a minimal setup (vimrc: only `Plug 'Houl/repmo-vim'` and repmo mappings).

**Comment by sunfanyunn** [comment]
Sorry that is not the one I am currently using.
I am actually trying to get repmo working with thiis repo:
https://github.com/leomao/pika-vim
Appreciate if you can help!

**Comment by Houl** [comment]
Please try again with a minimal setup,  `:h -u` (eg  `vim -N -u repmo_vimrc -U NONE -i NONE`, where the repmo_vimrc script sets up a `'runtimepath'` and mappings).
Maybe repmo does not work in a way you expect it to work.
When you get it to work in a minimal setup, then it's easier to spot conflicts in a larger setup.

**Comment by sunfanyunn** [comment]
I did try using the minimal setup. It does not work for me.
But I actually found out after adding this two lines, it worked.
```
noremap <expr> j repmo#Key('gj', 'gk')|sunmap j
noremap <expr> k repmo#Key('gk', 'gj')|sunmap k
```
Not sure why this is needed ... (thought it was optional

**Comment by Houl** [comment]
That's how it works ... you need to map `j` and `k` (and probably a lot more keys), otherwise these keys go undetected by `;` and `,`.

**Comment by sunfanyunn** [comment]
Yeah sry I sort of misunderstood when you said
```
if you like `:noremap j gj', you can keep that:
```
Btw, the following code segment also conflicts 

```

" Treat long lines as break lines (useful when moving around in them)
function! ToggleWrap()
  if &wrap
    echo "Wrap OFF"
    setlocal nowrap
  else
    echo "Wrap ON"
    setlocal wrap
    setlocal display+=lastline
  endif
  call SetWrapKeyMapping()
endfunction

function! SetWrapKeyMapping()
  if &wrap
    nnoremap  <buffer> <silent> k gk
    nnoremap  <buffer> <silent> j gj
    nnoremap  <buffer> <silent> 0 g^
    nnoremap  <buffer> <silent> $ g$
    nnoremap  <buffer> <silent> <Up>   gk
    nnoremap  <buffer> <silent> <Down> gj
    nnoremap  <buffer> <silent> <Home> g<Home>
    nnoremap  <buffer> <silent> <End>  g<End>
    inoremap <buffer> <silent> <Up>   <Esc>gka
    inoremap <buffer> <silent> <Down> <Esc>gja
    inoremap <buffer> <silent> <Home> <Esc>g<Home>i
    inoremap <buffer> <silent> <End>  <Esc>g<End>a
    onoremap <buffer> <silent> j gj
    onoremap <buffer> <silent> k gk
  else
    silent! nunmap <buffer> k
    silent! nunmap <buffer> j
    silent! nunmap <buffer> 0
    silent! nunmap <buffer> $
    silent! nunmap <buffer> <Up>
    silent! nunmap <buffer> <Down>
    silent! nunmap <buffer> <Home>
    silent! nunmap <buffer> <End>
    silent! iunmap <buffer> <Up>
    silent! iunmap <buffer> <Down>
    silent! iunmap <buffer> <Home>
    silent! iunmap <buffer> <End>
    silent! ounmap <buffer> j
    silent! ounmap <buffer> k
  endif
endfunction

au BufRead,BufNewFile * call SetWrapKeyMapping()
noremap <silent><F3> :call ToggleWrap()<CR>

```
I have to comment out this section so that it works with the repo I mentioned above. Thanks for the help.

**Comment by elig0n** [comment]
@Houl Why are you not providing basic bindings by default like in [the old script](https://www.vim.org/scripts/script.php?script_id=2174) ?
